version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: propertyhub-db
    ports:
      - '5442:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: propertyhub
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: propertyhub-redis
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    restart: always

volumes:
  pgdata:
  redisdata:
